---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      time: "05:00"
      timezone: Europe/London
      day: monday
  - package-ecosystem: terraform
    directory: /pubsub_subscription
    schedule:
      interval: weekly
      time: "05:00"
      timezone: Europe/London
      day: monday
  - package-ecosystem: terraform
    directory: /workload_identity_service_account
    schedule:
      interval: weekly
      time: "05:00"
      timezone: Europe/London
      day: monday
