---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      time: "05:00"
      timezone: Europe/London
      day: monday
    groups:
      all:
        patterns:
          - "*"
  - package-ecosystem: terraform
    directories:
      - /pubsub_subscription
      - /workload_identity_service_account
    schedule:
      interval: weekly
      time: "05:00"
      timezone: Europe/London
      day: monday
    groups:
      all:
        patterns:
          - "*"