---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      time: "05:00"
      timezone: Europe/London
      day: monday
    groups:
      all:
        patterns:
          - "*"
  - package-ecosystem: terraform
    directories:
      - /cert-manager
      - /cloud-sql-permissions
      - /cluster
      - /helm-provider
      - /opentelemetry-operator
      - /otel-sidecar-config
      - /project_network
      - /pubsub_subscription
      - /region
      - /workload_identity_service_account
    schedule:
      interval: weekly
      time: "05:00"
      timezone: Europe/London
      day: monday
    groups:
      all:
        patterns:
          - "*"
  - package-ecosystem: npm
    directories:
      - /cloud-sql-permissions/scripts/grant_sql_access
    schedule:
      interval: weekly
      time: "05:00"
      timezone: Europe/London
      day: monday
    groups:
      all:
        patterns:
          - "*"
