# docker run -e "USERID=$(id -u):$(id -g)" -v $(pwd):/lint -w /lint ghcr.io/antonbabenko/pre-commit-terraform:latest run --all-files
repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: "v1.89.1"
    hooks:
      - id: terraform_docs
        args:
          - --hook-config=--add-to-existing-file=true
      - id: terraform_docs_without_aggregate_type_defaults
      - id: terraform_fmt
      - id: terraform_validate
      - id: terraform_tflint
      - id: terraform_trivy
        args:
          - --args=--severity=MEDIUM,HIGH,CRITICAL
          - --args=--skip-dirs="**/.terraform"
